---
version: 2
project_name: git-wip
builds:
  - main: .
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--oidc-provider=github-actions"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes
    artifacts: all
    output: true
brews:
  - name: git-wip
    repository:
      owner: carhartl
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_PUBLISH_TOKEN }}"
